name: Run bot

on:
#  schedule:
#  - cron: 58 12 25 09 *
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Give perms to execute engines
        run: chmod +x ./engines/stockfish

      - name: Give perms to execute engines 2
        run: chmod +x ./engines/fairy-stockfish

      - name: Replace token
        run: |
          sed -i 's|BOT_TOKEN|${{ secrets.BOT_TOKEN }}|g' config.yml

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }} 
        run: python user_interface.py matchmaking
